/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package minis10;

import java.util.*;

/**
 *
 * @author VASUDHA SHAH
 */
public class jFRmain extends javax.swing.JFrame {
    ArrayList <Country> cList;
    ArrayList <Player> pList;
    ArrayList <Scores> sList;
     CountryDB cdb=new CountryDB();
     PlayerDB pdb=new PlayerDB();
     ScoreDB sdb=new ScoreDB();
    
    /**
     * Creates new form jFRmain
     */
    public jFRmain() {
        Console c=new Console();
        c.start();
        initComponents();

        cList=cdb.getCList();
        sList=sdb.getSList();
        pList=pdb.getPList();
        System.out.println(cList);
        for(int i=0;i<cList.size();i++)
        {
        jCB1.addItem(cList.get(i).getCname());
        }
        
       
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jCB2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jCB1 = new javax.swing.JComboBox<>();
        jL4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(2, 0));

        jLabel2.setText("player");

        jCB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB2ActionPerformed(evt);
            }
        });

        jLabel3.setText("country");

        jCB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jCB1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jCB2, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jL4, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCB1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCB2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jL4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jPanel1.add(jPanel2);

        jT1.setColumns(20);
        jT1.setRows(5);
        jScrollPane1.setViewportView(jT1);

        jPanel1.add(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB1ActionPerformed
        // TODO add your handling code here:
        int count=jCB1.getItemCount();
        jT1.setText("");
        jCB2.removeAllItems();
        if(jCB1.getSelectedIndex()==0)
        {
        for(int i=0;i<pList.size();i++)
        {
            if(pList.get(i).getCid()==1)
              jCB2.addItem(pList.get(i).getPname());
        }
        }
        else if(jCB1.getSelectedIndex()==1)
        {
        for(int i=0;i<pList.size();i++)
        {
            if(pList.get(i).getCid()==2)
            jCB2.addItem(pList.get(i).getPname());
        }
        }
        else if (jCB1.getSelectedIndex()==2)
        {
        for(int i=0;i<pList.size();i++)
        {
            if(pList.get(i).getCid()==3)
            jCB2.addItem(pList.get(i).getPname());
        }
        }
        
        System.out.println("--------"+count);
    }//GEN-LAST:event_jCB1ActionPerformed

    private void jCB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB2ActionPerformed
        // TODO add your handling code here:
        //////////////////////////
        jT1.setText("");
        if(jCB1.getSelectedIndex()==0 && jCB2.getSelectedIndex()==0)
        {int sum=0;
        for(int i=0;i<sList.size();i++)
        {
            if(sList.get(i).getPid()==1)
            { //jT1.setText("\n"+sList.get(i).getRuns());
                sum=sum+sList.get(i).getRuns();
                jT1.append("\n"+sList.get(i).getRuns());
              
            }
        }
        jL4.setText("RUNS SCORED BY VIRAT KOHLI:"+sum);
        }
        
        
        if(jCB1.getSelectedIndex()==0 && jCB2.getSelectedIndex()==1)
        {
            int sum=0;
        for(int i=0;i<sList.size();i++)
        {
            if(sList.get(i).getPid()==2)
            { //jT1.setText("\n"+sList.get(i).getRuns());
                sum=sum+sList.get(i).getRuns();
              jT1.append("\n"+sList.get(i).getRuns());
            }
        }
        jL4.setText("RUNS SCORED BY MSD:"+sum);
        }
        
        
        if(jCB1.getSelectedIndex()==0 && jCB2.getSelectedIndex()==2)
        {int sum=0;
        for(int i=0;i<sList.size();i++)
        {
            if(sList.get(i).getPid()==3)
            { //jT1.setText("\n"+sList.get(i).getRuns());
                sum=sum+sList.get(i).getRuns();
              jT1.append("\n"+sList.get(i).getRuns());
            }
        }
        jL4.setText("RUNS SCORED BY ROHIT SHARMA:"+sum);
        }
        
        
        if(jCB1.getSelectedIndex()==1 && jCB2.getSelectedIndex()==0)
        {int sum=0;
        for(int i=0;i<sList.size();i++)
        {
            if(sList.get(i).getPid()==4)
            { //jT1.setText("\n"+sList.get(i).getRuns());
                sum=sum+sList.get(i).getRuns();
              jT1.append("\n"+sList.get(i).getRuns());
            }
        }
        jL4.setText("RUNS SCORED BY DAVID WARNER:"+sum);
        }
        
        
        if(jCB1.getSelectedIndex()==1 && jCB2.getSelectedIndex()==1)
        {int sum=0;
        for(int i=0;i<sList.size();i++)
        {
            if(sList.get(i).getPid()==5)
            { //jT1.setText("\n"+sList.get(i).getRuns());
                sum=sum+sList.get(i).getRuns();
              jT1.append("\n"+sList.get(i).getRuns());
            }
        }
        jL4.setText("RUNS SCORED BY STEVE SMITH:"+sum);
        }
        
        if(jCB1.getSelectedIndex()==2 && jCB2.getSelectedIndex()==0)
        {int sum=0;
        for(int i=0;i<sList.size();i++)
        {
            if(sList.get(i).getPid()==6)
            { //jT1.setText("\n"+sList.get(i).getRuns());
                sum=sum+sList.get(i).getRuns();
                
              jT1.append("\n"+sList.get(i).getRuns());
            }
        }
        jL4.setText("RUNS SCORED BY GREME SMITH:"+sum);
        }
        
        if(jCB1.getSelectedIndex()==2 && jCB2.getSelectedIndex()==1)
        {int sum=0;
        for(int i=0;i<sList.size();i++)
        {
            if(sList.get(i).getPid()==7)
            { //jT1.setText("\n"+sList.get(i).getRuns());
                sum=sum+sList.get(i).getRuns();
                jT1.append("\n"+sList.get(i).getRuns());
            }
        }
        jL4.setText("RUNS SCORED BY HASIM AMLA:"+sum);
        }
        
        if(jCB1.getSelectedIndex()==2 && jCB2.getSelectedIndex()==2)
        {int sum=0;
        for(int i=0;i<sList.size();i++)
        {
            if(sList.get(i).getPid()==8)
            { //jT1.setText("\n"+sList.get(i).getRuns());
              sum=sum+sList.get(i).getRuns();
                jT1.append("\n"+sList.get(i).getRuns());
            }
        }
        jL4.setText("RUNS SCORED BY ABD:"+sum);
        }
        
        ////////////////////////////
    }//GEN-LAST:event_jCB2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFRmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFRmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFRmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFRmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFRmain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCB1;
    private javax.swing.JComboBox<String> jCB2;
    private javax.swing.JLabel jL4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jT1;
    // End of variables declaration//GEN-END:variables
}
